# Generated by Django 3.1.6 on 2021-03-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0002_auto_20210222_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False, verbose_name='작가 ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='작가')),
                ('recommend_yn', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1, verbose_name='추천 여부')),
                ('input_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='추천인')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('create_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='생성자id')),
                ('update_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='수정자id')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False, verbose_name='책 ID')),
                ('book_name', models.CharField(max_length=200, verbose_name='도서명')),
                ('author_name', models.CharField(max_length=200, verbose_name='작가')),
                ('summary', models.CharField(blank=True, max_length=4000, null=True, verbose_name='책소개')),
                ('recommend_yn', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1, verbose_name='추천 여부')),
                ('input_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='추천인')),
                ('read_date', models.DateField(null=True, verbose_name='완독일자')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('create_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='생성자id')),
                ('update_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='수정자id')),
                ('genre_cd', models.ForeignKey(db_column='genre_cd', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_book2', to='resume.comm_code', verbose_name='장르')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
