# Generated by Django 3.1.6 on 2021-02-23 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0002_auto_20210222_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False, verbose_name='작가 ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='작가 이름')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='사망일자')),
                ('summary', models.CharField(blank=True, max_length=4000, null=True, verbose_name='약력')),
                ('book_find_yn', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1, verbose_name='책 자동 찾기 여부')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('create_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='생성자id')),
                ('update_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='수정자id')),
                ('nation_cd', models.ForeignKey(db_column='nation_cd', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_author1', to='resume.comm_code', verbose_name='국적')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False, verbose_name='책 ID')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN')),
                ('book_name', models.CharField(max_length=200, verbose_name='책 이름')),
                ('publisher_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='출판사')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='출판일자')),
                ('summary', models.CharField(blank=True, max_length=4000, null=True, verbose_name='책소개')),
                ('book_url', models.CharField(blank=True, max_length=400, null=True, verbose_name='관련URL')),
                ('auto_update_yn', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=1, verbose_name='자동 update 완료 여부')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('create_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='생성자id')),
                ('update_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='수정자id')),
                ('author_id', models.ForeignKey(db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_book1', to='books.author', verbose_name='저자')),
                ('genre_cd', models.ForeignKey(db_column='genre_cd', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_book2', to='resume.comm_code', verbose_name='장르')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
