# Generated by Django 3.1.6 on 2021-03-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='log ID')),
                ('client_ip', models.CharField(blank=True, max_length=200, null=True, verbose_name='client ip')),
                ('log_gb', models.CharField(blank=True, max_length=200, null=True, verbose_name='로그 구분')),
                ('request_info', models.CharField(blank=True, max_length=2000, null=True, verbose_name='request정보')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
