# Generated by Django 3.1.6 on 2021-02-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='author',
            name='death_date',
        ),
        migrations.AddField(
            model_name='author',
            name='birth_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='탄생년도'),
        ),
        migrations.AddField(
            model_name='author',
            name='death_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='사망년도'),
        ),
    ]
