# Generated by Django 3.1.6 on 2021-03-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='user정보'),
        ),
    ]
