# Generated by Django 3.1.6 on 2021-03-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210320_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_book',
            fields=[
                ('Author_book_id', models.AutoField(primary_key=True, serialize=False, verbose_name='작가 도서 ID')),
                ('author_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='작가')),
                ('book_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='도서명')),
                ('pub_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='출판일')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='이미지URL')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('create_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='생성자id')),
                ('update_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='수정자id')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
