# Generated by Django 3.1.6 on 2021-03-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_book',
            name='author_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='작가 ID'),
        ),
    ]
