# Generated by Django 3.1.6 on 2021-02-12 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comm_code',
            fields=[
                ('comm_code', models.AutoField(primary_key=True, serialize=False, verbose_name='공통코드')),
                ('comm_code_name', models.CharField(max_length=200, verbose_name='공통코드명')),
                ('ref_field', models.CharField(blank=True, max_length=200, null=True, verbose_name='참조필드')),
                ('display_order', models.IntegerField(blank=True, null=True, verbose_name='표시 순서')),
                ('use_yn', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1, verbose_name='사용여부')),
                ('summary', models.CharField(blank=True, max_length=2000, null=True, verbose_name='비고')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('create_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='생성자id')),
                ('update_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='수정자id')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comm_div',
            fields=[
                ('comm_div_id', models.AutoField(primary_key=True, serialize=False, verbose_name='공통코드 구분 ID')),
                ('comm_div_name', models.CharField(max_length=200, verbose_name='공통코드 구분')),
                ('summary', models.CharField(blank=True, max_length=2000, null=True, verbose_name='비고')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('create_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='생성자id')),
                ('update_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='수정자id')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edu_his',
            fields=[
                ('edu_his_id', models.AutoField(primary_key=True, serialize=False, verbose_name='교육이력ID')),
                ('summary', models.CharField(blank=True, max_length=2000, null=True, verbose_name='비고')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('create_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='생성자id')),
                ('update_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='수정자id')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False, verbose_name='사원ID')),
                ('emp_name', models.CharField(max_length=200, verbose_name='사원명')),
                ('gender', models.CharField(choices=[('m', '남'), ('f', '여')], default='m', max_length=1, verbose_name='성별')),
                ('birthdate', models.DateField(null=True, verbose_name='생년월일')),
                ('mobile_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='모바일번호')),
                ('emergency_telno', models.CharField(blank=True, max_length=50, null=True, verbose_name='비상연락처')),
                ('emergency_rel', models.CharField(blank=True, max_length=50, null=True, verbose_name='비상연락처 관계')),
                ('email_addr', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('postno', models.CharField(blank=True, max_length=50, null=True, verbose_name='우편번호')),
                ('addr', models.CharField(blank=True, max_length=400, null=True, verbose_name='주소')),
                ('addr_dtl', models.CharField(blank=True, max_length=200, null=True, verbose_name='상세주소')),
                ('indate', models.DateField(null=True, verbose_name='입사일자')),
                ('outdate', models.DateField(blank=True, null=True, verbose_name='퇴사일자')),
                ('work_base_date', models.DateField(blank=True, null=True, verbose_name='경력 기간 산정 기준일')),
                ('work_base_year', models.IntegerField(blank=True, null=True, verbose_name='기초 경력 년수')),
                ('work_base_month', models.IntegerField(blank=True, null=True, verbose_name='기초 경력 개월수')),
                ('skill_main', models.CharField(blank=True, max_length=2000, null=True, verbose_name='전문분야')),
                ('skill_major', models.CharField(blank=True, max_length=2000, null=True, verbose_name='주요사업')),
                ('summary', models.CharField(blank=True, max_length=2000, null=True, verbose_name='비고')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('create_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='생성자id')),
                ('update_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='수정자id')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='License_his',
            fields=[
                ('license_his_id', models.AutoField(primary_key=True, serialize=False, verbose_name='자격증이력ID')),
                ('got_date', models.DateField(null=True, verbose_name='취득일')),
                ('summary', models.CharField(blank=True, max_length=2000, null=True, verbose_name='비고')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('create_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='생성자id')),
                ('update_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='수정자id')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order_comp',
            fields=[
                ('order_comp_id', models.AutoField(primary_key=True, serialize=False, verbose_name='발추처ID')),
                ('order_comp_name', models.CharField(max_length=200, verbose_name='발주처')),
                ('summary', models.CharField(blank=True, max_length=2000, null=True, verbose_name='비고')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('create_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='생성자id')),
                ('update_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='수정자id')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pjt',
            fields=[
                ('pjt_id', models.AutoField(primary_key=True, serialize=False, verbose_name='프로젝트ID')),
                ('pjt_name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, '길이가 너무 짧습니다.')], verbose_name='사업명')),
                ('pjt_start_date', models.DateField(blank=True, null=True, verbose_name='프로젝트 시작일자')),
                ('pjt_end_date', models.DateField(blank=True, null=True, verbose_name='프로젝트 종료일자')),
                ('use_skill', models.CharField(blank=True, max_length=500, null=True, verbose_name='개발환경')),
                ('summary', models.CharField(blank=True, max_length=2000, null=True, verbose_name='비고')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('create_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='생성자id')),
                ('update_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='수정자id')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pjt_his',
            fields=[
                ('pjt_his_id', models.AutoField(primary_key=True, serialize=False, verbose_name='프로젝트이력ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='근무처')),
                ('join_start_date', models.DateField(null=True, verbose_name='참여 시작일자')),
                ('join_end_date', models.DateField(null=True, verbose_name='참여 종료일자')),
                ('pjt_role', models.CharField(max_length=200, null=True, verbose_name='프로젝트 역할')),
                ('summary', models.CharField(blank=True, max_length=2000, null=True, verbose_name='비고')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('create_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='생성자id')),
                ('update_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='수정자id')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School_his',
            fields=[
                ('school_his_id', models.AutoField(primary_key=True, serialize=False, verbose_name='학력이력ID')),
                ('school_name', models.CharField(max_length=200, verbose_name='학교')),
                ('school_subject', models.CharField(max_length=200, verbose_name='학과')),
                ('graduate_date', models.DateField(blank=True, null=True, verbose_name='졸업일자')),
                ('summary', models.CharField(blank=True, max_length=2000, null=True, verbose_name='비고')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('create_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='비고')),
                ('update_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='비고')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vw_emp',
            fields=[
                ('EMP_ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='사번')),
                ('POSITION_NAME', models.CharField(max_length=200, verbose_name='직위')),
                ('EMP_NAME', models.CharField(max_length=200, verbose_name='사원명')),
                ('SKILL_GRADE', models.CharField(max_length=200, verbose_name='등급')),
                ('AVAIL_STATE', models.CharField(max_length=200, verbose_name='가동상태')),
                ('AVAIL_MONTH', models.CharField(max_length=200, verbose_name='투입가능 시점')),
                ('GENDER', models.CharField(max_length=200, verbose_name='성별')),
                ('BIRTHDATE', models.DateField(verbose_name='생년월일')),
                ('AGE', models.CharField(max_length=200, verbose_name='연령(만)')),
                ('JUMIN', models.CharField(max_length=200, verbose_name='주민번호')),
                ('LAST_SCHOOL', models.CharField(max_length=200, verbose_name='최종학력')),
                ('ADDR', models.CharField(max_length=200, verbose_name='주소')),
                ('INDATE', models.DateField(verbose_name='입사일자')),
                ('OUTDATE', models.DateField(verbose_name='퇴사일자')),
                ('INDATE_PERIOD', models.CharField(max_length=200, verbose_name='입사일 기준 경력 기간')),
                ('OTHER_COMP_YN', models.CharField(max_length=200, verbose_name='타사경력 존재여부')),
                ('TOTAL_PERIOD', models.CharField(max_length=200, verbose_name='전체 경력 기간')),
                ('EVIDENCE_METHOD', models.CharField(max_length=200, verbose_name='경력 증빙 점검 방법')),
                ('INFO_LICENSE_YN', models.CharField(max_length=200, verbose_name='정보처리기사')),
                ('OTHER_LICENSE', models.CharField(max_length=1000, verbose_name='기타 자격증')),
                ('REQUEST_YN_YN', models.CharField(max_length=200, verbose_name='위탁교육')),
                ('OTHER_EDU', models.CharField(max_length=1000, verbose_name='기타교육')),
                ('SUMMARY', models.CharField(max_length=2000, verbose_name='비고')),
            ],
            options={
                'db_table': 'VW_EMP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Work_his',
            fields=[
                ('work_his_id', models.AutoField(primary_key=True, serialize=False, verbose_name='경력이력ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='회사명')),
                ('work_start_date', models.DateField(null=True, verbose_name='경력시작일자')),
                ('work_end_date', models.DateField(blank=True, null=True, verbose_name='경력종료일자')),
                ('emp_position', models.CharField(max_length=200, verbose_name='직위')),
                ('work_part', models.CharField(max_length=200, verbose_name='담당업무')),
                ('summary', models.CharField(blank=True, max_length=2000, null=True, verbose_name='비고')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('create_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='생성자id')),
                ('update_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='수정자id')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('edu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='교육ID')),
                ('edu_name', models.CharField(max_length=200, verbose_name='교육명')),
                ('edu_start_date', models.DateField(null=True, verbose_name='시작일')),
                ('edu_end_date', models.DateField(null=True, verbose_name='종료일')),
                ('request_yn', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=1, verbose_name='위탁교육')),
                ('agency_name', models.CharField(max_length=200, verbose_name='기관명')),
                ('summary', models.CharField(blank=True, max_length=2000, null=True, verbose_name='비고')),
                ('create_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('update_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('create_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='생성자id')),
                ('update_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='수정자id')),
            ],
            options={
                'permissions': [('can_edit', 'Can edit')],
                'managed': True,
            },
        ),
    ]
