# Generated by Django 3.1.6 on 2021-02-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'managed': True, 'permissions': [('can_edit', 'Can edit'), ('read_only', 'Read only')]},
        ),
    ]
