# Generated by Django 3.1.6 on 2021-02-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vw_emp',
            table='vw_emp',
        ),
    ]
